services:
  - type: web
    name: rea-certificate-api
    runtime: docker
    repo: https://github.com/maretaayu/rea-certificate
    env: docker
    dockerfilePath: ./ai-engineering-certificate/Dockerfile
    dockerContext: ./ai-engineering-certificate
    region: singapore
    plan: free
